custom_attributes:
    BDId: ''
    BDURL: ''
    RqTitle: ''
    RqParent: ''
    ReqRationale: ''
    RqLevel: 'None'
    RqType: 'Info'
    RqSources: ''
    RqChapter: ''
    RqTarget: ''
    RqValue: ''
    RqVar: ''
    RqStatus: ''
    
published_custom_attributes: ['BDId','BDURL','RqTitle','RqParent','ReqRationale','RqLevel','RqType','RqSources','RqChapter','RqTarget','RqValue','RqVar','RqStatus']
custom_attr_format_string: '- **{}:** {}'
required_version: 'NRT Doorstop v1.5.1'
